rules = {
    'animation': ['webkit', 'moz'],
    'animation-name': ['webkit', 'moz'],
    'animation-duration': ['webkit', 'moz'],
    'animation-timing-function': ['webkit', 'moz'],
    'animation-delay': ['webkit', 'moz'],
    'animation-iteration-count': ['webkit', 'moz'],
    'animation-direction': ['webkit', 'moz'],
    'animation-play-state': ['webkit', 'moz'],
    'animation': ['webkit', 'moz'],
    'appearance': ['webkit', 'moz'],
    'backface-visibility': ['webkit', 'moz'],
    'background-clip': ['webkit'],
    'border-image': ['webkit', 'o'],
    'box-align': ['webkit', 'moz'],
    'box-direction': ['webkit', 'moz'],
    'box-flex': ['webkit', 'moz'],
    'box-ordinal-group': ['webkit', 'moz'],
    'box-orient': ['webkit', 'moz'],    
    'box-pack': ['webkit', 'moz'],
    'box-sizing': ['webkit', 'moz'],
    'column-count': ['webkit', 'moz'],
    'column-gap': ['webkit', 'moz'],
    'column-rule': ['webkit', 'moz'],
    'column-span': ['webkit'],
    'column-width': ['webkit', 'moz'],
    'columns': ['webkit', 'moz'],
    'keyframes': ['webkit', 'moz', 'o'],
    'perspective': ['webkit'],
    'perspective-origin': ['webkit'],
    'transform': ['webkit', 'moz', 'ms', 'o'],
    'transform-origin': ['webkit', 'moz', 'ms', 'o'],
    'transform-style': ['webkit'],
    'transition': ['webkit', 'moz', 'o'],
    'transition-property': ['webkit', 'moz', 'o'],
    'transition-duration': ['webkit', 'moz', 'o'],
    'transition-timing-function': ['webkit', 'moz', 'o'],
    'transition-delay': ['webkit', 'moz', 'o']
}